name: Trigger auto deployment for cnx02

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - 'https:/github.com/Telefonica/Eternalblue-Doublepulsar-Metasploit/blob/master/**'
    - '.github/workflows/cnx02-AutoDeployTrigger-1b778fc0-a5a0-47eb-b2de-1041cf29e4a8.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: github.com/Telefonica/Eternalblue-Doublepulsar-Metasploit/blob/master/Dockerfile
          username: ${{ secrets.CNX02_REGISTRY_USERNAME }}
          password: ${{ secrets.CNX02_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: github.com/Telefonica/Eternalblue-Doublepulsar-Metasploit/blob/master/Dockerfile/cnx02:${{ github.sha }}
          file: https://github.com/Telefonica/Eternalblue-Doublepulsar-Metasploit/blob/master/Dockerfile
          context: https://github.com/Telefonica/Eternalblue-Doublepulsar-Metasploit/blob/master/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CNX02_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n cnx02 -g Cluster --server github.com/Telefonica/Eternalblue-Doublepulsar-Metasploit/blob/master/Dockerfile --username  ${{ secrets.CNX02_REGISTRY_USERNAME }} --password ${{ secrets.CNX02_REGISTRY_PASSWORD }}
            az containerapp update -n cnx02 -g Cluster --image github.com/Telefonica/Eternalblue-Doublepulsar-Metasploit/blob/master/Dockerfile/cnx02:${{ github.sha }}
